/*
 * MIRAS STJÄRNSAFARI – core
 * ---------------------------------------------------------------------
 * Mira's own game: a photo safari in a tiger-striped gondola across
 * floating islands, to help a lost tiger cub find her mother.
 *
 * The game is loaded on demand (see the loader in index.html) from these
 * files, in order:
 *   sprites/atlas.js   frame map for the PNG sprite sheets (generated by
 *                      scripts/build-mira-sprites.mjs)
 *   mira-core.js       helpers, sprites, pixel canvas, particles, saving
 *   mira-content.js    animals, islands, story texts, music (all Swedish)
 *   mira-world.js      skies, floating islands, cable and gondola
 *   mira-scenes.js     the ride, photos, tools, fishing and story scenes
 *   mira-ui.js         menus, HUD, album and the controller
 *
 * Everything is drawn at a low resolution (about 210 px on the short side)
 * and scaled up by a whole number, so the pixel art stays crisp.
 */
(function () {
    'use strict';

    const MS = (window.MiraSafari = window.MiraSafari || {});

    // =====================================================================
    // Helpers
    // =====================================================================
    const TAU = Math.PI * 2;
    const clamp = (v, a, b) => (v < a ? a : v > b ? b : v);
    const lerp = (a, b, t) => a + (b - a) * t;
    const smooth = (t) => t * t * (3 - 2 * t);
    const easeOut = (t) => 1 - Math.pow(1 - t, 3);
    const easeInOut = (t) => (t < 0.5 ? 4 * t * t * t : 1 - Math.pow(-2 * t + 2, 3) / 2);

    function rng(seed) {
        let s = (seed >>> 0) || 1;
        const next = () => {
            s ^= s << 13;
            s ^= s >>> 17;
            s ^= s << 5;
            return (s >>> 0) / 4294967296;
        };
        next.range = (a, b) => a + (b - a) * next();
        next.int = (a, b) => Math.floor(a + (b - a + 1) * next());
        next.pick = (list) => list[Math.floor(next() * list.length)];
        next.chance = (p) => next() < p;
        return next;
    }

    // Smooth 1-D value noise (deterministic)
    function noise1(seed) {
        const r = rng(seed);
        const table = new Float32Array(512);
        for (let i = 0; i < 512; i += 1) table[i] = r() * 2 - 1;
        return (x) => {
            const i = Math.floor(x);
            const f = x - i;
            const a = table[i & 511];
            const b = table[(i + 1) & 511];
            return lerp(a, b, smooth(f));
        };
    }

    function hexToRgb(hex) {
        const h = hex.replace('#', '');
        return [parseInt(h.slice(0, 2), 16), parseInt(h.slice(2, 4), 16), parseInt(h.slice(4, 6), 16)];
    }

    function rgbToHex([r, g, b]) {
        const p = (v) => Math.round(clamp(v, 0, 255)).toString(16).padStart(2, '0');
        return `#${p(r)}${p(g)}${p(b)}`;
    }

    function mixHex(a, b, t) {
        const A = hexToRgb(a);
        const B = hexToRgb(b);
        return rgbToHex([lerp(A[0], B[0], t), lerp(A[1], B[1], t), lerp(A[2], B[2], t)]);
    }

    // 4×4 ordered dither matrix, for pixel-art gradients
    const BAYER = [0, 8, 2, 10, 12, 4, 14, 6, 3, 11, 1, 9, 15, 7, 13, 5].map((v) => (v + 0.5) / 16);
    const dither = (x, y) => BAYER[(y & 3) * 4 + (x & 3)];

    function makeCanvas(w, h) {
        const c = document.createElement('canvas');
        c.width = Math.max(1, Math.ceil(w));
        c.height = Math.max(1, Math.ceil(h));
        const g = c.getContext('2d');
        g.imageSmoothingEnabled = false;
        return c;
    }

    MS.util = { TAU, clamp, lerp, smooth, easeOut, easeInOut, rng, noise1, hexToRgb, rgbToHex, mixHex, dither, makeCanvas };

    // =====================================================================
    // Sprite atlas
    // =====================================================================
    // Each frame: [sheet, x, y, w, h, anchorX, anchorY, boundsX, boundsY, boundsW, boundsH, points?]
    const atlas = {
        images: [],
        sprites: null,
        ready: null,

        load(base) {
            if (this.ready) return this.ready;
            const data = window.MIRA_ATLAS;
            if (!data) return Promise.reject(new Error('Mira atlas missing'));
            this.sprites = data.sprites;
            this.ready = Promise.all(data.sheets.map((file, i) => new Promise((resolve, reject) => {
                const img = new Image();
                img.onload = () => {
                    this.images[i] = img;
                    resolve();
                };
                img.onerror = () => reject(new Error(`Could not load ${file}`));
                img.src = `${base}sprites/${file}`;
            })));
            return this.ready;
        },

        has(name, anim) {
            const s = this.sprites && this.sprites[name];
            return !!(s && (anim === undefined || (s[anim] && s[anim].length)));
        },

        frames(name, anim) {
            const s = this.sprites && this.sprites[name];
            return (s && s[anim]) || null;
        },

        frame(name, anim, index = 0) {
            const list = this.frames(name, anim);
            if (!list || !list.length) return null;
            return list[((index % list.length) + list.length) % list.length];
        },

        /** Draw a frame with its anchor at (x, y). Coordinates are rounded to whole pixels. */
        draw(g, name, anim, index, x, y, flip = false, alpha = 1) {
            const f = this.frame(name, anim, index);
            if (!f) return null;
            this.drawFrame(g, f, x, y, flip, alpha);
            return f;
        },

        drawFrame(g, f, x, y, flip = false, alpha = 1) {
            const img = this.images[f[0]];
            if (!img) return;
            x = Math.round(x);
            y = Math.round(y);
            if (alpha !== 1) g.globalAlpha = alpha;
            if (!flip) {
                g.drawImage(img, f[1], f[2], f[3], f[4], x - f[5], y - f[6], f[3], f[4]);
            } else {
                g.save();
                g.translate(x + f[5] + 1, y - f[6]);
                g.scale(-1, 1);
                g.drawImage(img, f[1], f[2], f[3], f[4], 0, 0, f[3], f[4]);
                g.restore();
            }
            if (alpha !== 1) g.globalAlpha = 1;
        },

        /** Screen-space box of the opaque pixels of a frame drawn at (x, y). */
        box(f, x, y, flip = false) {
            if (!f) return null;
            x = Math.round(x);
            y = Math.round(y);
            const [, , , w, , ax, ay, bx, by, bw, bh] = f;
            const left = flip ? x + ax - (bx + bw) + 1 : x - ax + bx;
            return { x: left, y: y - ay + by, w: bw, h: bh };
        },

        /** A named point of a frame (e.g. 'hand') in screen space. */
        point(f, name, x, y, flip = false) {
            const pts = f && f[11];
            if (!pts || !pts[name]) return null;
            const [px, py] = pts[name];
            return { x: flip ? Math.round(x) + f[5] - px : Math.round(x) - f[5] + px, y: Math.round(y) - f[6] + py };
        },

        /** Copy a frame into its own small canvas (for DOM icons and the album). */
        toCanvas(name, anim, index = 0, scale = 1) {
            const f = this.frame(name, anim, index);
            if (!f) return null;
            const c = makeCanvas(f[3] * scale, f[4] * scale);
            const g = c.getContext('2d');
            g.imageSmoothingEnabled = false;
            g.drawImage(this.images[f[0]], f[1], f[2], f[3], f[4], 0, 0, f[3] * scale, f[4] * scale);
            return c;
        }
    };
    MS.atlas = atlas;

    // =====================================================================
    // The pixel view: a low-resolution canvas scaled up by a whole number
    // =====================================================================
    const view = {
        canvas: null,
        g: null,
        w: 320,
        h: 208,
        scale: 1,
        dpr: 1,
        portrait: false,
        targetShort: 212,

        init(canvas) {
            this.canvas = canvas;
            // The canvas is tiny (about 430×240), so drawing on the CPU is fast and
            // avoids GPU stalls; it also makes grabbing photos from it instant.
            this.g = canvas.getContext('2d', { alpha: false, willReadFrequently: true });
            this.resize();
        },

        resize() {
            const dpr = clamp(window.devicePixelRatio || 1, 1, 4);
            const cssW = Math.max(1, window.innerWidth);
            const cssH = Math.max(1, window.innerHeight);
            const devW = Math.round(cssW * dpr);
            const devH = Math.round(cssH * dpr);
            const short = Math.min(devW, devH);
            const scale = Math.max(1, Math.round(short / this.targetShort));
            const w = Math.ceil(devW / scale);
            const h = Math.ceil(devH / scale);
            this.dpr = dpr;
            this.scale = scale;
            this.portrait = cssH > cssW;
            if (this.canvas.width !== w || this.canvas.height !== h) {
                this.canvas.width = w;
                this.canvas.height = h;
            }
            this.w = w;
            this.h = h;
            this.canvas.style.width = `${(w * scale) / dpr}px`;
            this.canvas.style.height = `${(h * scale) / dpr}px`;
            this.g.imageSmoothingEnabled = false;
            return this;
        },

        /** CSS pixel position (clientX/Y) -> view pixel. */
        toView(clientX, clientY) {
            const r = this.canvas.getBoundingClientRect();
            return {
                x: ((clientX - r.left) / r.width) * this.w,
                y: ((clientY - r.top) / r.height) * this.h
            };
        },

        /** View pixel -> CSS pixel position (for placing DOM things over the canvas). */
        toCss(x, y) {
            const r = this.canvas.getBoundingClientRect();
            return { x: r.left + (x / this.w) * r.width, y: r.top + (y / this.h) * r.height };
        }
    };
    MS.view = view;

    // =====================================================================
    // Tiny pixel icons for particles (drawn once)
    // =====================================================================
    const PIX = {};
    function pixelIcon(rows, key) {
        const h = rows.length;
        const w = rows[0].length;
        const c = makeCanvas(w, h);
        const g = c.getContext('2d');
        rows.forEach((row, y) => {
            for (let x = 0; x < w; x += 1) {
                const col = key[row[x]];
                if (!col) continue;
                g.fillStyle = col;
                g.fillRect(x, y, 1, 1);
            }
        });
        return c;
    }

    function buildPixels() {
        PIX.heart = pixelIcon(['.ab.ab.', 'abbbbbc', 'bbbbbbc', '.bbbbc.', '..bbc..', '...c...'], { a: '#ffc1d4', b: '#ff5d8f', c: '#c9376b' });
        PIX.heartSmall = pixelIcon(['a.a', 'bbb', '.b.'], { a: '#ff8fb1', b: '#ff4f86' });
        PIX.note = pixelIcon(['..aa', '..ab', '..a.', '..a.', 'aaa.', 'aaa.'], { a: '#fff4c2', b: '#fff4c2' });
        PIX.note2 = pixelIcon(['.aaaa', '.a..a', '.a..a', 'aa.aa', 'aa.aa'], { a: '#c9f1ff' });
        PIX.sparkle = pixelIcon(['..a..', '..b..', 'abcba', '..b..', '..a..'], { a: '#fff4b0', b: '#ffe46a', c: '#ffffff' });
        PIX.sparkleSmall = pixelIcon(['.a.', 'aba', '.a.'], { a: '#ffe46a', b: '#ffffff' });
        PIX.star = pixelIcon(['...a...', '..aba..', 'aabbbaa', '.abbba.', '.ab.ba.', 'aa...aa'], { a: '#f2a900', b: '#ffe46a' });
        PIX.dust = pixelIcon(['ab', 'bb'], { a: '#fff6e0', b: '#e8d4b0' });
        PIX.drop = pixelIcon(['a', 'b'], { a: '#e6fbff', b: '#7fd3ff' });
        PIX.leaf = pixelIcon(['.a', 'ab', 'b.'], { a: '#8fdc5a', b: '#4e9b3a' });
        PIX.petal = pixelIcon(['ab', 'b.'], { a: '#ffe3f0', b: '#ff9cc6' });
        PIX.snow = pixelIcon(['.a.', 'aba', '.a.'], { a: '#dfeaff', b: '#ffffff' });
        PIX.crumb = pixelIcon(['a'], { a: '#ffe8a8' });
        PIX.chip = pixelIcon(['ab'], { a: '#f0cf9a', b: '#b07a4a' });
        PIX.bang = pixelIcon(['.aa.', '.aa.', '.aa.', '.a..', '....', '.a..'], { a: '#ffffff' });
        PIX.zz = pixelIcon(['aaa.', '..a.', '.a..', 'aaa.'], { a: '#dfe8ff' });
        PIX.smoke = pixelIcon(['.aa.', 'abba', 'abba', '.aa.'], { a: '#e8e4f0', b: '#ffffff' });
        PIX.apple = pixelIcon(['..b.', '.aa.', 'aaac', 'aaac', '.cc.'], { a: '#ff4a4a', b: '#6b3b1e', c: '#b32234' });
    }
    MS.PIX = PIX;

    // =====================================================================
    // Particles (world space)
    // =====================================================================
    const fx = {
        list: [],
        max: 420,
        reduced: false,

        reset() {
            this.list.length = 0;
        },

        spawn(icon, x, y, { vx = 0, vy = 0, life = 1, gravity = 0, drag = 0, fade = true, wobble = 0, delay = 0, layer = 1, blink = false } = {}) {
            if (this.list.length >= this.max) this.list.shift();
            this.list.push({ icon, x, y, vx, vy, life, age: -delay, gravity, drag, fade, wobble, seed: Math.random() * 10, layer, blink });
        },

        burst(icon, x, y, n, { speed = 40, spread = TAU, angle = -Math.PI / 2, life = 0.8, gravity = 60, drag = 1.5 } = {}) {
            const count = this.reduced ? Math.ceil(n / 2) : n;
            for (let i = 0; i < count; i += 1) {
                const a = angle + (Math.random() - 0.5) * spread;
                const v = speed * (0.4 + Math.random() * 0.8);
                this.spawn(icon, x, y, { vx: Math.cos(a) * v, vy: Math.sin(a) * v, life: life * (0.7 + Math.random() * 0.6), gravity, drag });
            }
        },

        update(dt) {
            for (let i = this.list.length - 1; i >= 0; i -= 1) {
                const p = this.list[i];
                p.age += dt;
                if (p.age < 0) continue;
                if (p.age >= p.life) {
                    this.list.splice(i, 1);
                    continue;
                }
                p.vy += p.gravity * dt;
                if (p.drag) {
                    const k = Math.max(0, 1 - p.drag * dt);
                    p.vx *= k;
                    p.vy *= k;
                }
                p.x += p.vx * dt;
                p.y += p.vy * dt;
            }
        },

        draw(g, camX, camY, layer = 1) {
            for (const p of this.list) {
                if (p.age < 0 || p.layer !== layer) continue;
                const t = p.age / p.life;
                if (p.fade && t > 0.7 && Math.floor(p.age * 20) % 2 === 0) continue;   // pixel-style flicker out
                if (p.blink && Math.floor(p.age * 8) % 2 === 1) continue;
                const icon = PIX[p.icon] || p.icon;
                if (!icon) continue;
                const wob = p.wobble ? Math.sin(p.age * 6 + p.seed) * p.wobble : 0;
                g.drawImage(icon, Math.round(p.x - camX + wob - icon.width / 2), Math.round(p.y - camY - icon.height / 2));
            }
        }
    };
    MS.fx = fx;

    // =====================================================================
    // Saved progress
    // =====================================================================
    const STORE_KEY = 'miraStjarnsafari.v1';
    const store = {
        data: null,

        fresh() {
            return {
                v: 1,
                chapter: 0,             // how far the story has come (islands finished)
                started: false,
                finished: false,
                tools: [],              // 'apple', 'fishing', 'flute', 'bubbles'
                album: {},              // species id -> { stars, moments: [], photo, n }
                fish: {},               // fish id -> { n, best }
                outfit: 'c',            // starts in her summer-evening clothes, like on the bench
                outfits: ['c'],
                sfx: true,
                music: true,
                speech: true
            };
        },

        load() {
            this.data = this.fresh();
            try {
                const raw = window.localStorage.getItem(STORE_KEY);
                if (raw) {
                    const saved = JSON.parse(raw);
                    if (saved && saved.v === 1) this.data = Object.assign(this.fresh(), saved);
                }
            } catch (error) {
                // private mode or blocked storage: play without saving
            }
            return this.data;
        },

        save() {
            try {
                window.localStorage.setItem(STORE_KEY, JSON.stringify(this.data));
                return true;
            } catch (error) {
                // Storage full (photos are the big part): drop the photos of the
                // oldest album entries and try once more.
                try {
                    const entries = Object.values(this.data.album).filter((e) => e.photo);
                    entries.slice(0, Math.ceil(entries.length / 3)).forEach((e) => { e.photo = null; });
                    window.localStorage.setItem(STORE_KEY, JSON.stringify(this.data));
                    return true;
                } catch (again) {
                    return false;
                }
            }
        },

        reset() {
            this.data = this.fresh();
            this.save();
        }
    };
    MS.store = store;

    MS.buildPixels = buildPixels;
})();
